version: '3.9'

services:
  mongo_db:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    volumes:
      - mongo_db:/data/db
    ports:
      - ${MONGODB_PORT}:27017

  fastapi:
    container_name: fastapi_container
    build: .
    ports:
      - "${SERVER_PORT}:8000"
    depends_on:
      - mongo_db
    environment:
      - PORT=${SERVER_PORT}
      - MONGODB_URI=${MONGODB_URI}
      - DB_NAME=${DB_NAME}
    volumes:
      - .:/app/fastapi

volumes:
  mongo_db: {}